/**
 * Grill mobile app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.lr2.apiclient.models


/**
 * 
 * @param id 
 * @param name 
 * @param idImage 
 * @param price 
 * @param weight 
 */
data class AdditionModel (

    val id: kotlin.Int,
    val name: kotlin.String,
    val idImage: kotlin.Int,
    val price: kotlin.Int,
    val weight: kotlin.Int
) : java.io.Serializable