/**
 * Grill mobile app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.lr2.apiclient.models


/**
 *
 * @param idUser
 * @param street
 * @param home
 * @param flat
 * @param comment
 * @param homeName
 */
data class AddressDataModel (

    val idUser: kotlin.Int,
    val street: kotlin.String,
    val home: kotlin.String,
    val flat: kotlin.String,
    val comment: kotlin.String,
    val homeName: kotlin.String
) : java.io.Serializable