/**
 * Grill mobile app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.lr2.apiclient.models


/**
 *
 * @param idDishCategory
 * @param name
 * @param imageId
 */
data class DishCategoryDataModel (

    val idDishCategory: kotlin.Int,
    val name: kotlin.String,
    val image_id: kotlin.Int
) : java.io.Serializable