/**
 * Grill mobile app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.lr2.apiclient.models


/**
 * 
 * @param idPoint 
 * @param x 
 * @param y 
 * @param address 
 */
data class RestaurantModel (

    val idPoint: kotlin.Int,
    val x: java.math.BigDecimal,
    val y: java.math.BigDecimal,
    val address: kotlin.String
) : java.io.Serializable