/**
 * Grill mobile app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.lr2.apiclient.apis

import com.example.lr2.apiclient.infrastructure.ApiClient
import com.example.lr2.apiclient.infrastructure.ClientError
import com.example.lr2.apiclient.infrastructure.ClientException
import com.example.lr2.apiclient.infrastructure.RequestConfig
import com.example.lr2.apiclient.infrastructure.RequestMethod
import com.example.lr2.apiclient.infrastructure.ResponseType
import com.example.lr2.apiclient.infrastructure.ServerError
import com.example.lr2.apiclient.infrastructure.ServerException
import com.example.lr2.apiclient.infrastructure.Success
import com.example.lr2.apiclient.models.RestaurantModel

class RestaurantApi(basePath: kotlin.String = "http://10.0.2.2:8080") : ApiClient(basePath) {

    /**
     * get restaurants
     * 
     * @return kotlin.Array<RestaurantModel>
     */
    @Suppress("UNCHECKED_CAST")
    fun getRestaurants(): kotlin.Array<RestaurantModel> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/restaurants"
        )
        val response = request<kotlin.Array<RestaurantModel>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<RestaurantModel>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
